#!/bin/bash
#
# Input the template number
#
read -p " Kérlek add meg a DXF fájl nevének hosszát Pl.: 1-7, vagy 2-6  : " template
#
# HTML codes: Head, Paragraph, Headings, Tail
#
head="
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>
<body>
"
#
p1="<p>"
p2="</p>"
#
h1="<h2>"
h2="</h2>"
#
img1="<img src=\""
img2="\">"
#
t="
</body>
</html>
"
#
lr="Sablon      lv      darab"
#
# Function: based on pic2html
#
function pictohtml {
# Fill the array from part.txt
#
readarray array < part.txt
#
# At this point put together the html file
#
echo "$head" > $msz.html
echo "$h1" >> $msz.html
echo "Munkaszám: $msz" >> $msz.html
echo "$h2" >> $msz.html
echo "$p1" >> $msz.html
echo "$lr" >> $msz.html
echo "$p2" >> $msz.html
count=0
while [ "x${array[count]}" != "x" ]
do
      count2=$(( $count + 1 ))
      row=$(head part.txt -n $count2 | tail -n 1)
#      pic=$(head part.txt -n $count2 | tail -n 1 | cut -c 1-7 | cut -d "S" -f2 | cut -c 2-6)
      pic=$(head part.txt -n $count2 | tail -n 1 | cut -c $template)
      picname=$(ls ../bmp/*.BMP | grep $pic | tail -n 1 | xargs basename)
      if [ -z $picname ]
         then
         echo " A $pic BMP kép hiányzik. Kérlek másold be a BMP képet a ../bmp/ könyvtárba."
#         rm -r html
         exit 1 # Exit if any BMP file is not exist.
      fi
      find ../bmp/ -type f -name $picname -exec cp -p {} . \; # Copy the BMP files to the html folder
      echo "$p1" >> $msz.html
      echo "$row" >> $msz.html
      echo "$p2" >> $msz.html
      echo "$p1" >> $msz.html
      echo "$img1" >> $msz.html
      echo "$picname" >> $msz.html
      echo "$img2" >> $msz.html
      echo "$p2" >> $msz.html
      count=$(( $count + 1 ))
done
echo "$t" >> $msz.html
}
#
# Create all folder
#
mkdir -p $(cat folder.txt | cut -c 1-10)
#
# Its just a temp file
#
ls -d */ | grep -v bmp | cut -d "/" -f1 > tmp.txt
#
# Read folder names from temp file
#
readarray farray < tmp.txt
#
# Delete temp file
#
rm tmp.txt
#
# Create temporary the part.txt, and run the function.
#
e=0
while [ "z${farray[e]}" != "z" ]
do
        echo "################################################################################"
        echo ""
        echo " Ugrás a" ${farray[e]} "könyvtárba, és a html fájl létrehozása."
	echo ""
        cd ${farray[e]}
#	echo $PWD
	touch part.txt
	msz=`pwd | xargs basename`
	i=0
	db=`cat ../folder.txt | grep $msz | wc -l`
#	echo " $db alkatrész van a szedőlapon."
	while [ $i != $db ]
	do
		i2=$(( $i + 1 ))
		cat ../folder.txt | grep $msz | head -n $i2 | tail -n 1 | cut -d "S" -f2 >> part.txt
		i=$(( $i + 1 ))
	done
	e=$(( $e + 1 ))
	pictohtml # Run function
	rm part.txt # Delete part.txt
	cd ..
done
echo "################################################################################"
echo ""
echo " Összesen " $e " html fájl készítettem."
echo " A következő html fájlok készültek el."
echo ""
find -type f -name "*.html" | sort -d
echo ""
echo "################################################################################"
exit 0
