#!/bin/bash
exec 2>/dev/null
#
# Check that the part.txt file is exists, and that it is not empty
#
if [ ! -s part.txt ]
   then
   echo ""
   echo " A part.txt nincs létrehozva,vagy üres a fájl."
   echo " A part.txt létrehozása."
   touch part.txt
   echo " Kész"
   echo " Az part.txt az alábbi módon nézzen ki."
   echo ""
   echo "S04077  10B     400db"
   echo "S04078  8B      200db"
   echo "S04079  8B      200db"
   echo ""
   echo " A part.txt csak annyi sorbon álljon ahány készterméket akarunk rakni a szedőlapra."
   echo " Kérlek másold bele az adatokat a part.txt fájlba."
   exit
fi
#
# jobnumer, piece of part, piece of BMP
#
msz=`pwd | xargs basename`
echo ""
echo " A szedőlap száma: $msz"
#
db=`cat part.txt | wc -l`
echo " A késztermékek száma: $db db"
#
#picdb=`ls *.BMP | wc -l`
#if [ $picdb = 0 ]
#   then
#   echo " A BMP képek hiányoznak. Kérlek másold be a BMP képeket a jelenlegi könyvtárba."
#   exit
#fi
#echo " A képek száma : $picdb db"
#
# The part number not equal with the BMP files number
#
#if [ $db != $picdb ]
#   then
#   echo " A késztermékek száma nem eggyezik meg a képek számával."
#   echo " Valamelyik BMP kép kétszer szerepel a könyvtárban, vagy a part.txt hiányos."
#   exit
#fi
#
# Check the html folder. If not exist: create. If exist: Delete all file in the html folder
#
if [ ! -d html ]
   then
   echo " A html könyvtár nem létezik, ezért most létre lesz hozva."
   mkdir html
   else
   echo " A html könyvtár létezik. A benne lévő fájlok törlődnek ! ! !"
   rm html/*
fi
#
# Fill the array from part.txt
#
readarray array < part.txt
#
# HTML codes: Head, Paragraph, Headings, Tail
#
head="
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>
<body>
"                                      
#
p1="<p>"                                                        
p2="</p>"                                                       
#
h1="<h2>"
h2="</h2>"
#
img1="<img src=\""                                              
img2="\">"                                                      
#
t="
</body>
</html>
"                                                               
#
# Name header
#
lr="Sablon	lv	darab"
#
# At this point put together the html file 
#
echo "$head" > html/$msz.html           
echo "$h1" >> html/$msz.html
echo "Munkaszám: $msz" >> html/$msz.html
echo "$h2" >> html/$msz.html
echo "$p1" >> html/$msz.html
echo "$lr" >> html/$msz.html
echo "$p2" >> html/$msz.html
#
count=0
while [ "x${array[count]}" != "x" ]
do
      count2=$(( $count + 1 ))
      row=$(head part.txt -n $count2 | tail -n 1)
#     pic=$(head part.txt -n $count2 | tail -n 1 | cut -c 3-6)
      pic=$(head part.txt -n $count2 | tail -n 1 | cut -c 1-7 | cut -d "S" -f2 | cut -c 2-6)
#      picname=$(ls *.BMP | grep $pic)
      picname=$(ls ../bmp/*.BMP | grep $pic | tail -n 1 | xargs basename)
      find ../bmp/ -type f -name $picname -exec cp -p {} html/ \;
      if [ -z $picname ]
         then
         echo " A $pic BMP kép hiányzik. Kérlek másold be a $pic BMP képet a jelenlegi könyvtárba."
         rm -r html
         exit
      fi
      echo "$p1" >> html/$msz.html
      echo "$row" >> html/$msz.html
      echo "$p2" >> html/$msz.html
      echo "$p1" >> html/$msz.html
      echo "$img1" >> html/$msz.html
      echo "$picname" >> html/$msz.html
      echo "$img2" >> html/$msz.html
      echo "$p2" >> html/$msz.html
      count=$(( $count + 1 ))
done
echo "$t" >> html/$msz.html
#
# Copy the BMP files to the html folder
#
#find *.BMP -exec cp -p {} html/ \;
html_file=`ls html/*.html | xargs basename`
echo ""
echo " A BMP fájlok átmásolva a html könyvtárba."
echo " A $html_file fájl létrehozva a html könyvtárba."
echo ""
