#!/bin/bash
exec 2>/dev/null
dirs=$(find . -maxdepth 1 -type d -printf '%P\n')
#
# 
#
if [ ! -s jobnum.txt ]
   then
   echo ""
   echo " A jobnum.txt nincs létrehozva, vagy üres a fájl."
   echo " A jobnum.txt létrehozása."
   touch jobnum.txt
   echo " Kész"
   echo " A jobnum.txt csak egy sorból állhat és csak egy számsort tartalmazhat."
   echo " Pl.: 1740017792 "
   echo " Kérlek másold bele a munkaszámot a jobnum.txt fájlba."
   exit
fi
#
#
#
if [ ! -s part.txt ]
   then
   echo ""
   echo " A part.txt nincs létrehozva,vagy üres a fájl."
   echo " A part.txt létrehozása."
   touch part.txt
   echo " Kész"
   echo " Az part.txt az alábbi módon nézzen ki."
   echo ""
   echo "S04077  10B     400db"
   echo "S04078  8B      200db"
   echo "S04079  8B      200db"
   echo ""
   echo " A part.txt csak annyi sorbon álljon ahány készterméket akarunk rakni a szedőlapra."
   echo " Kérlek másold bele az adatokat a part.txt fájlba."
   exit
fi
#
#
#
msz=`cat jobnum.txt`
echo ""
echo " A szedőlap száma: $msz"
#
db=`cat part.txt | wc -l`
echo " A késztermékek száma: $db db"
#
picdb=`ls *.BMP | wc -l`
if [ $picdb = 0 ]
   then
   echo " A BMP képek hiányoznak. Kérlek másold be a BMP képeket a jelenlegi könyvtárba."
   exit
fi
echo " A képek száma : $picdb db"
#
#
#
if [ $db != $picdb ]
   then
   echo " A késztermékek száma nem eggyezik meg a képek számával."
   echo " Valamelyik BMP kép kétszer szerepel a könyvtárban, vagy a part.txt hiányos."
   exit
fi
#
#
#
if [ ! -d html ]
   then
   echo " A html könyvtár nem létezik, ezért most létre lesz hozva."
   mkdir html
   else
   echo " A html könyvtár létezik. A benne lévő fájlok törlődnek ! ! !"
   rm html/*
fi
#
#
#
readarray array < part.txt
#
#
#
head="
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>
<body>
"                                      
#
p1="<p>"                                                        
p2="</p>"                                                       
#
h1="<h2>"
h2="</h2>"
#
img1="<img src=\""                                              
img2="\">"                                                      
#
t="
</body>
</html>
"                                                               
#
#
#
lr="Sablon	lv	darab"
#
#
#
echo "$head" > html/$msz.html           
echo "$h1" >> html/$msz.html
echo "Munkaszám: $msz" >> html/$msz.html
echo "$h2" >> html/$msz.html
echo "$p1" >> html/$msz.html
echo "$lr" >> html/$msz.html
echo "$p2" >> html/$msz.html
#
#
#
count=0
while [ "x${array[count]}" != "x" ]
do
      count2=$(( $count + 1 ))
      row=$(head part.txt -n $count2 | tail -n 1)
      pic=$(head part.txt -n $count2 | tail -n 1 | cut -c 3-6)
      picname=$(ls *.BMP | grep $pic)
      if [ -z $picname ]
         then
         echo " A $pic BMP kép hiányzik. Kérlek másold be a $pic BMP képet a jelenlegi könyvtárba."
         rm -r html
         exit
      fi
      echo "$p1" >> html/$msz.html
      echo "$row" >> html/$msz.html
      echo "$p2" >> html/$msz.html
      echo "$p1" >> html/$msz.html
      echo "$img1" >> html/$msz.html
      echo "$picname" >> html/$msz.html
      echo "$img2" >> html/$msz.html
      echo "$p2" >> html/$msz.html
      count=$(( $count + 1 ))
done
echo "$t" >> html/$msz.html
#
#
#
find *.BMP -exec cp -p {} html/ \;
html_file=`ls html/*.html | xargs basename`
echo ""
echo " A BMP fájlok átmásolva a html könyvtárba."
echo " A $html_file fájl létrehozva a html könyvtárba."
echo ""
